author:
  name: 'Lana Milanovich'
  email: lana.milanovich@gmail.com
  github: lanami
  linkedin: lana-milanovich

# Site
title: 'Lana Milanovich'
description: 'Really great description'

# Configuration
url: ''
baseurl: ''
google_analytics: ''
permalink: pretty

# Build
gems:
  - jekyll-feed
  - octopress-autoprefixer

markdown: kramdown
exclude: ['vendor', '.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE.txt', 'README.md', s3_website.yml]