# You
name: "Lana Milanovich"
email: lana.milanovich@gmail.com

#Social
github: lanami
linkedin: lana-milanovich
facebook: 
twitter:

# Site
title: "Lana Milanovich"
description: "Really great description"

# Configuration
url: ""
baseurl: ""
google_analytics:

# Build
gems: [octopress-autoprefixer]
markdown: kramdown
exclude: ['_screenshots', '.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE.txt', 'README.md']